// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAnXaZiNSoP2CcxwL3SCHnagLuv_2VSHo',
    appId: '1:792161722138:web:bc0b80bfe5897c6a4216a3',
    messagingSenderId: '792161722138',
    projectId: 'do-important',
    authDomain: 'do-important.firebaseapp.com',
    storageBucket: 'do-important.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVWhYLd9fQDbkNGVxNmsKbWuq30UKaCfg',
    appId: '1:792161722138:android:92605c6e2a0bd28a4216a3',
    messagingSenderId: '792161722138',
    projectId: 'do-important',
    storageBucket: 'do-important.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMAdf7KftWS959Ui2F5aUacLIP1Kqofcg',
    appId: '1:792161722138:ios:cc916472479e0d574216a3',
    messagingSenderId: '792161722138',
    projectId: 'do-important',
    storageBucket: 'do-important.appspot.com',
    iosBundleId: 'com.example.doImportantZanovo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMAdf7KftWS959Ui2F5aUacLIP1Kqofcg',
    appId: '1:792161722138:ios:8b633f21f040183d4216a3',
    messagingSenderId: '792161722138',
    projectId: 'do-important',
    storageBucket: 'do-important.appspot.com',
    iosBundleId: 'com.example.doImportantZanovo.RunnerTests',
  );
}
